# name: Trigger Remote Workflow

# on:
#   pull_request:
#     branches: [main]  # Runs when a PR is made to the main branch

# jobs:
#   trigger:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v3

#       - name: current dir
#         run: pwd; ls -la ; tree 2>/dev/null
#       - name: Send Trigger Request to Remote Repo
#         run: |
#           curl -X POST https://api.github.com/repos/Rocky9991905/UmV2aWV3/dispatches \
#             -H "Accept: application/vnd.github.v3+json" \
#             -H "Authorization: token ${{ secrets.PAT_OF_GITHUB }}" \
#             -d '{
#               "event_type": "external_pr",
#               "client_payload": {
#                 "pr_url": "'"${{ github.event.pull_request.html_url }}"'"
#               }
#             }'

name: Trigger Remote Workflow

on:
  pull_request:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Show current directory
        run: pwd && ls -la && tree 2>/dev/null

      - name: Send Trigger Request to Remote Repo
        run: |
          curl -X POST https://api.github.com/repos/Rocky9991905/UmV2aWV3/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_OF_GITHUB }}" \
            -d '{
              "event_type": "external_pr",
              "client_payload": {
                "command_for_running_application": "docker compose up",
                "github_token_for_peroxide": "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",
                "gemini_api_key":"AIzaSyAfGwfrEkj8fXjALdqF2Ih2Xik11gbSFc0",
                "Delay_in_seconds":"60",
                "location_from_where_we_have_to_execute_the_command": samples,
                "path_of_script.sh": ".",
                "ports": "5000 1639",
                "buildDelay":"60",
                "repo": "${{ github.repository }}",
                "pr_url": "${{ github.event.pull_request.html_url }}",
                "pr_number": "${{ github.event.number }}"
              }
            }'

