name: Trigger Remote Workflow

on:
  pull_request:
    branches: [main]  # Runs when a PR is made to the main branch

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send Trigger Request to Remote Repo
        env:
          GH_PAT: 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  # Store a Personal Access Token in Secrets
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token $GH_PAT" \
            --data '{"event_type": "external_pr", "client_payload": { "pr_url": "${{ github.event.pull_request.html_url }}" }}' \
            https://api.github.com/repos/Rocky9991905/UmV2aWV3/dispatches
