name: Trigger Remote Workflow

on:
  pull_request:
    branches: [main]  # Runs when a PR is made to the main branch

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: login
        run: gh auth login 
      - name: Send Trigger Request to Remote Repo
        run: |
              gh api repos/Rocky9991905/UmV2aWV3/dispatches \
                --method POST \
                --input - <<EOF
              {
                "event_type": "external_pr",
                "client_payload": {
                  "pr_url": "${{ github.event.pull_request.html_url }}"
                }
              }
              EOF
