name: Trigger Remote Workflow

on:
  pull_request:
    branches: [main]  # Runs when a PR is made to the main branch

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send Trigger Request to Remote Repo
        run: |
          curl -X POST https://api.github.com/repos/Rocky9991905/UmV2aWV3/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_OF_GITHUB }}" \
            -d '{
              "event_type": "external_pr",
              "client_payload": {
                "pr_url": "'"${{ github.event.pull_request.html_url }}"'"
              }
            }'
