name: Trigger Remote Workflow

on:
  pull_request:
    branches: [main]  # Runs when a PR is made to the main branch

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: current dir
        run: pwd; ls -la ; tree 2>/dev/null
      - name: now
        run: find /home/runner/work/Review/ -type f -name "main.py" ; echo "above"
      - name: Send Trigger Request to Remote Repo
        run: |
          curl -X POST https://api.github.com/repos/Rocky9991905/UmV2aWV3/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.PAT_OF_GITHUB }}" \
            -d '{
              "event_type": "external_pr",
              "client_payload": {
                "pr_url": "'"${{ github.event.pull_request.html_url }}"'"
              }
            }'
